/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package pythy.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BLANK = 1;
  /** RegularExpression Id. */
  int TAB = 2;
  /** RegularExpression Id. */
  int NEWLINE = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int ELSE = 5;
  /** RegularExpression Id. */
  int WHERE = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int ADD = 10;
  /** RegularExpression Id. */
  int SUB = 11;
  /** RegularExpression Id. */
  int TIME = 12;
  /** RegularExpression Id. */
  int DIV_INT = 13;
  /** RegularExpression Id. */
  int DIV_FLOAT = 14;
  /** RegularExpression Id. */
  int LP = 15;
  /** RegularExpression Id. */
  int RP = 16;
  /** RegularExpression Id. */
  int ECHO = 17;
  /** RegularExpression Id. */
  int BOOL = 18;
  /** RegularExpression Id. */
  int NAME = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int FLOAT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"if\"",
    "\"else\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"//\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"echo\"",
    "<BOOL>",
    "<NAME>",
    "<INT>",
    "<FLOAT>",
    "\"=\"",
    "\":\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
  };

}
